let arr = [
	{
		'name':'审核',
		'path':'Check',
		'icon':'',
		'showType':3,
		'index':'/home/Check',
		'isSon':true,
		'list':[
			{
				'name':'艺人审核',
				'path':'/home/artistCheck',
				'icon':'',
				'index':'/home/artistCheck',
				'isSon':false
			},
			{
				'name':'音乐审核',
				'path':'/home/musicCheck',
				'icon':'',
				'index':'/home/musicCheck',
				'isSon':false
			},
			{
				'name':'主题审核',
				'path':'/home/themeCheck',
				'icon':'',
				'index':'/home/themeCheck',
				'isSon':false
			},
			{
				'name':'评论审核',
				'path':'/home/commentCheck',
				'icon':'',
				'index':'/home/commentCheck',
				'isSon':false
			},
			{
				'name':'审核设置',
				'path':'/home/setCheck',
				'icon':'',
				'index':'/home/setCheck',
				'isSon':false
			}
		]
	},
	{
		'name':'星球信息',
		'path':'PlanetInformation',
		'icon':'',
		'showType':4,
		'index':'/home/planetinformation',
		'isSon':false
	},
	{
		'name':'机构管理',
		'path':'OrganizationManage',
		'icon':'',
		'showType':4,
		'index':'/home/OrganizationManage',
		'isSon':false
	},
	{
		'name':'艺人管理',
		'path':'ArtistManage',
		'icon':'',
		'showType':4,
		'index':'/home/ArtistManage',
		'isSon':false
	},
	{
		'name':'收入管理',
		'path':'Income',
		'icon':'',
		'showType':99,
		'index':'/home/income',
		'isSon':true,
		'list':[
			{
				'name':'我的收益',
				'path':'/home/income',
				'icon':'',
				'index':'/home/income',
				'isSon':false
			},
			{
				'name':'收入榜单',
				'path':'/home/incomelist',
				'icon':'',
				'index':'/home/incomelist',
				'isSon':false
			}
		]
	},
	{
		'name':'居民管理',
		'path':'PeopleManage',
		'icon':'',
		'showType':4,
		'index':'/home/PeopleManage',
		'isSon':false
	},
	{
		'name':'账号管理',
		'path':'AccountManage',
		'icon':'',
		'showType':99,
		'index':'/home/AccountManage',
		'isSon':false
	},
	{
		'name':'活动设置',
		'path':'ActivitiesSet',
		'icon':'',
		'showType':5,
		'index':'/home/ActivitiesSet',
		'isSon':false
	},
	{
		'name':'数据分析',
		'path':'RecordData',
		'icon':'',
		'showType':5,
		'index':'/home/RecordData',
		'isSon':true,
		'list':[
			{
				'name':'趋势分析',
				'path':'RecordData',
				'icon':'',
				'index':'/home/RecordData',
				'isSon':false
			},
			{
				'name':'用户数据',
				'path':'UserData',
				'icon':'',
				'index':'/home/UserData',
				'isSon':false
			},
			{
				'name':'播放数据',
				'path':'PlayData',
				'icon':'',
				'index':'/home/PlayData',
				'isSon':false
			},
			{
				'name':'访问量统计',
				'path':'AccessData',
				'icon':'',
				'index':'/home/AccessData',
				'isSon':false
			},
			{
				'name':'完播率数据',
				'path':'BroadcastData',
				'icon':'',
				'index':'/home/BroadcastData',
				'isSon':false
			}
		]
	},
	{
		'name':'标签管理',
		'path':'LabelManagement',
		'icon':'',
		'showType':5,
		'index':'/home/LabelManagement',
		'isSon':false
	},
	{
		'name':'星歌管理',
		'path':'StarSong',
		'icon':'',
		'showType':5,
		'index':'/home/StarSong',
		'isSon':false
	},
	{
		'name':'音乐榜单',
		'path':'MusicList',
		'icon':'',
		'showType':5,
		'index':'/home/MusicList',
		'isSon':false
	},
	{
		'name':'用户管理',
		'path':'UserAdmin',
		'icon':'',
		'showType':5,
		'index':'/home/UserAdmin',
		'isSon':false
	},
	{
		'name':'设置',
		'path':'AdminSetting',
		'icon':'',
		'showType':5,
		'index':'/home/AdminSetting',
		'isSon':true,
		'list':[
			{
				'name':'奖励设置',
				'path':'AdminSetting',
				'icon':'',
				'index':'/home/AdminSetting',
				'isSon':false
			},
			{
				'name':'版本设置',
				'path':'VersionSetting',
				'icon':'',
				'index':'/home/VersionList',
				'isSon':false
			},
			{
				'name':'评论设置',
				'path':'CommentSetting',
				'icon':'',
				'index':'/home/CommentList',
				'isSon':false
			},
			{
				'name':'主题设置',
				'path':'ThemeSetting',
				'icon':'',
				'index':'/home/ThemeList',
				'isSon':false
			},
			{
				'name':'用户设置',
				'path':'UserSetting',
				'icon':'',
				'index':'/home/UserList',
				'isSon':false
			}
		]
	}
];
export  default arr;